general:
  clientUrl: ""
  secret: ""
  rsaPrivateKey: ""

database:
  connectionString: ""

s3:
  url: ""
  username: ""
  password: ""
  bucket: ""
  region: ""

mail:
  enabled: ""
  name: ""
  email: ""
  provider: ""
  smtp:
    host: ""
    port: ""
    security: ""
    username: ""
    password: ""
